service: mememaker

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

package:
  individually: true #afirma que deve fazer o deploy em pastas diferentes 
  excludeDevDependencies: true  #remove dev dependencias(puglins...)

exclude: #exclue pra nao ir na lambda
  - ./dependencies
  - ./dependencies.zip #ja vai na layer
  - ./mock/ #pasta pra teste


functions:
  mememaker:
    handler: app/handler.mememaker
    layers:
      - {Ref: GmLibaryLambdaLayer}
    events:
      - http:
          path: mememaker
          method: get

layers:
  GmLibary:
    path: dependencies
    package: #aqui informa que vai pegar o zip como layer e nao mandar a pasta toda
      artifact: dependencies.zip